In [30]:
class Car:
    car__count=0
    def __init__(self,name,cc,birth):
        self.__name=name
        self.__cc=cc
        self.__birth=birth
        Car.car__count+=1
    def find(self):
        print(self.__name)
    def correction(self):
        name=input("이름:")
        self.__name=name
    def size(self):
        if self.__cc <1000:
            print("소형")
        elif 1000<=self.__cc<=2000:
            print("중형")
        elif 2000<self.__cc:
            print("대형")
    @classmethod
    def carCount(cls):
        print("총 자동차는:",Car.car__count)
        
            
        
        
        

In [31]:
mycar = Car("avante",1500,"2020")

In [32]:
mycar.carCount()

총 자동차는: 1


In [33]:
mycar.find()

avante


In [34]:
mycar.correction()

이름:소나타


In [35]:
mycar.find()

소나타


In [36]:
mycar.size()

중형


In [37]:
mycar2=Car("그랜져",3000,"2020")

In [38]:
mycar.carCount()

총 자동차는: 2


In [39]:
names= """강다영
강동아
권윤택
김광희
김기범
김성희
김수진
김태익
남윤호
박수진
박창서
선은빈
송은이
우지원
윤현수
윤호준
이송재
이한비
조계철
최하은
황호영
조성혜"""

In [41]:
import pickle

try:
    with open("data3.p","rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pickle.load(file)
        print(name, address, email)
except:
    name=input("이름:")
    address=input("주소:")
    email=input("이메일:")
    with open("data3.p","wb") as file:
        pickle.dump(name, file)
        pickle.dump(address, file)
        pickle.dump(email, file)
        
        


김기범 서울 aa@aa.com


In [71]:
class NotNumber(Exception):
    def __init__(self):
        super().__init__("잘못된 숫자입니다.")
def gugudan(num):

        if 1<num<10:
            for i in range(1,10):
                print(f"{num}*{i}={num*i}")
        else:
            raise NotNumber
    
            
try:
    gugudan(2)
except Exception as e:
           print("NotNumber:",e)    

2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18


In [72]:
try:
    gugudan(1)
except Exception as e:
           print("NotNumber:",e) 

NotNumber: 잘못된 숫자입니다.


In [73]:
try:
    gugudan(10)
except Exception as e:
           print("NotNumber:",e) 

NotNumber: 잘못된 숫자입니다.


In [57]:
x = [1, 2, 3]
try:
    print(10/0)
    x[5]
except ZeroDivisionError as e:
    print("숫자를 0으로 나눌수 없음", e)
except IndexError as e:
    print("잘못된 인덱스", e)


숫자를 0으로 나눌수 없음 division by zero


In [1]:
import pkcalc.calc as calc

print(calc.name)

calc


In [3]:
print(calc.sub(5,6))

-1


In [4]:
import sys
print(sys.path)

['C:\\Users\\721\\kdigital', 'C:\\Users\\721\\anaconda3\\python38.zip', 'C:\\Users\\721\\anaconda3\\DLLs', 'C:\\Users\\721\\anaconda3\\lib', 'C:\\Users\\721\\anaconda3', '', 'C:\\Users\\721\\anaconda3\\lib\\site-packages', 'C:\\Users\\721\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\721\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\721\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\721\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\721\\.ipython']


In [1]:
import pkcalc

calc package


In [4]:
print(add(5,6))

11


In [5]:
from pkcalc.calc import add, sub
print(add(5,6))

11


In [8]:
import numpy as np

In [9]:
import pandas as pd

In [15]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]
#matrix원소의 합
matrix_1[0][1]

2

In [17]:
new_matrix=[]
for i in range(len(matrix_1)):
    temp=[]
    a=matrix_1[i][0]+matrix_2[i][0]
    b=matrix_1[i][1]+matrix_2[i][1]
    temp.append(a)
    temp.append(b)
    new_matrix.append(temp)
print(new_matrix)
    

[[6, 8], [10, 12]]


In [18]:
for i in range(len(matrix_1)):
    matrix_1[i][0]+=1
    matrix_1[i][1]+=1

In [19]:
matrix_1

[[2, 3], [4, 5]]

In [3]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]
new_matrix=[]
for i in range(len(matrix_1)):
    temp=[]
    for j in range(len(matrix_1[i])):
        temp.append(matrix_1[i][j]+matrix_2[i][j])
    new_matrix.append(temp)
print(new_matrix)
        

[[6, 8], [10, 12]]


In [2]:
matrix_1 = [[1,2],[3,4]]
for i in range(len(matrix_1)):
    for j in range(len(matrix_1[i])):
        matrix_1[i][j]+=1
print(matrix_1)

[[2, 3], [4, 5]]


In [6]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]
def sum_mat(mat_1,mat_2):
    new_matrix=[]
    for i in range(len(mat_1)):
        temp=[]
        for j in range(len(mat_1[i])):
            temp.append(matrix_1[i][j]+matrix_2[i][j])
        new_matrix.append(temp)
    return new_matrix
new_matrix = sum_mat(matrix_1,matrix_2)
print(new_matrix)

[[6, 8], [10, 12]]


In [10]:
mat_sum=np.array(matrix_1) + np.array(matrix_2)
print(mat_sum)

[[ 6  8]
 [10 12]]


In [11]:
mat_one_plus = np.array(matrix_1) + 1
mat_one_plus

array([[2, 3],
       [4, 5]])

In [17]:
import time
size= 10000000

x = list(range(size))
y = list(range(size))



In [18]:
print(time.localtime())

time.struct_time(tm_year=2020, tm_mon=12, tm_mday=15, tm_hour=17, tm_min=24, tm_sec=27, tm_wday=1, tm_yday=350, tm_isdst=0)


In [20]:
start_time=time.time()
z= [ x[i] + y [i] for i in range(size)]
print(f"리스트 걸린시간 :{time.time()- start_time}")

리스트 걸린시간 :2.000378370285034


In [25]:
x = np.arange(size)
y = np.arange(size)

In [28]:
s_time=time.time()
z= x + y
print(f"리스트 걸린시간 :{time.time()- s_time}")

리스트 걸린시간 :0.03223919868469238


In [37]:
x= np.uint(64)
print(x)
print(type(x))
print(x.dtype)

64
<class 'numpy.uint32'>
uint32


In [35]:
x= np.array([1,2,3,4])
print(x)
print(type(x))


[1 2 3 4]
<class 'numpy.ndarray'>


In [38]:
x = np.float32([1,2,3,4])
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [39]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)
print(type(x))
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [41]:
x=np.int32(x)
print(x.dtype)
np.issubdtype(x.dtype,np.int32)

int32


True

In [42]:
x=np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [43]:
x= x.reshape(3,3)

In [44]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
x = np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [47]:
x= np.array([[1,2],[3,4],[5,6]])

In [48]:
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(x.reshape(2,3))


[[1 2 3]
 [4 5 6]]


In [50]:
x= np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
