In [14]:
class Character:
    def __init__(self):
        self.hp =200
    def move(self):
        self.hp-=10
    def rest(self):
        self.hp+=10
    def checkHealth(self):
        print("health: ", self.hp)
    
class Knight(Character):
    def __init__(self):
        super().__init__()
    def move(self):
        self.hp-=15
    def attack(self):
        print("공격합니다.")
    

In [20]:
knight_1=Knight()
knight_1.move()
knight_1.checkHealth()

health:  185


In [23]:

class Healer(Character):
    def __init__(self):
        super().__init__()
        self.mana = 100
    def heal(self,character):
        self.mana-=10
        character.rest()
    def checkMana(self):
        print("현재 mana : ", self.mana)
        
    

In [24]:
healer_1 = Healer()

healer_1.checkHealth()

health:  200


In [25]:
knight_2 = Knight()
knight_2.move()
knight_2.move()
knight_2.checkHealth()

health:  170


In [26]:
person = Character()
person.move()
person.move()
person.checkHealth()


health:  180


In [27]:
healer_1.checkMana()
knight_1.checkHealth()
healer_1.heal(knight_1)
knight_1.checkHealth()
healer_1.heal(knight_2)
knight_2.checkHealth()
healer_1.heal(person)
person.checkHealth()


현재 mana :  100
health:  185
health:  195
health:  180
health:  190


In [28]:
import numpy as np


In [29]:
x = np.linspace(1, 20, 5)

In [30]:
x

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [31]:
x= np.linspace(1,100,3)
x

array([  1. ,  50.5, 100. ])

In [32]:
x = np.arange(20)
print(x[1:3])


[1 2]


In [33]:
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
print(x[1:3, 1:3])

[[ 6  7]
 [11 12]]


In [35]:
print(x[1:3, 1:2])

[[ 6]
 [11]]


In [36]:
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


In [37]:
a = np.arange(20).reshape(4, 5)
print(a[1][1])

6


In [38]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [39]:
print(a[1,1])

6


In [40]:
print(a[[1,1],[1,2]])

[6 7]


In [41]:
print(a>3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [42]:
print(a[a>3])


[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
print(a[a==1])

[1]


In [45]:
print(a[~(a==1)])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [48]:
print(a[(a>3)&(a<8)])


[4 5 6 7]


In [49]:
np.random.rand(5,5)

array([[0.36644487, 0.86044486, 0.76878102, 0.75586522, 0.28160043],
       [0.31687967, 0.89670259, 0.48765685, 0.25161776, 0.45340571],
       [0.21893873, 0.70913933, 0.01925052, 0.3002744 , 0.92595147],
       [0.47077247, 0.85386227, 0.32443203, 0.57424343, 0.51375388],
       [0.04149185, 0.3258777 , 0.22444237, 0.93584516, 0.41843087]])

In [50]:
np.random.randint(1,10)

3

In [51]:
np.random.randint(1,10,size=(5))

array([6, 2, 6, 1, 2])

In [53]:
x=np.random.randint(1,10,size=(5,3))
x

array([[9, 6, 8],
       [8, 3, 7],
       [8, 2, 4],
       [1, 3, 4],
       [1, 2, 1]])

In [54]:
x.ravel()

array([9, 6, 8, 8, 3, 7, 8, 2, 4, 1, 3, 4, 1, 2, 1])

In [55]:
x.ravel(order="C")

array([9, 6, 8, 8, 3, 7, 8, 2, 4, 1, 3, 4, 1, 2, 1])

In [56]:
x.ravel(order="F")

array([9, 8, 8, 1, 1, 6, 3, 2, 3, 2, 8, 7, 4, 4, 1])

In [57]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [64]:
x = np.arange(1, 4)
y = np.arange(4, 7)


array([4, 5, 6])

In [62]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [66]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [70]:
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
np.split(x,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [72]:
x = np.arange(16).reshape(4, 4)

In [73]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [75]:
x = np.arange(16).reshape(4, 4)

In [76]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [85]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [88]:
y=np.arange(30,60).reshape(2,5,3)
y

array([[[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [89]:
np.split(x, 2, axis=1)

ValueError: array split does not result in an equal division

In [90]:
np.concatenate([x, y],axis=1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [94]:
x=np.arange(4).reshape(2,2)
y=np.arange(4).reshape(2,2)
x.dot(y)

array([[ 2,  3],
       [ 6, 11]])

In [95]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [96]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [97]:
np.linalg.det(x)

-2.0

In [98]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [112]:
x=np.array(x)

In [105]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
y=np.array(y)

In [115]:
x=x.reshape(3,3)

In [116]:
y=y.reshape(3,3)

In [117]:
sum_xy=x+y

In [118]:
sum_xy

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [119]:
multi_xy=x*y

In [120]:
multi_xy

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [121]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
y

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [123]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [124]:
x= np.linspace(1,20,30)
x

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [125]:
y=10
sum_10=x+y

In [126]:
sum_10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [129]:
x=np.random.randint(1, 100, size=(2,10, 10))

In [130]:
x

array([[[25, 64,  3, 16, 84, 63, 52, 99, 65, 34],
        [64, 51, 76, 33, 77,  3, 37, 67, 57, 17],
        [71, 90, 97, 98, 28, 33, 20, 44, 71, 89],
        [ 9,  3, 38, 15, 34,  1, 29, 57, 17, 21],
        [86, 89, 52, 71, 84, 96, 27,  6, 15, 41],
        [59, 13,  6, 41,  3, 68, 14, 94, 15, 49],
        [45, 53, 48, 31, 26, 66, 84, 92, 16, 15],
        [32, 70, 22, 74, 21, 66, 93, 44, 79, 77],
        [37, 18, 19, 69, 76, 97, 25, 88, 49, 73],
        [41, 50, 44, 24, 79, 18, 86, 22, 78, 39]],

       [[63, 22, 44, 68, 51, 15, 33, 64, 49, 74],
        [98, 94,  4, 40,  1, 12, 45, 26, 38, 68],
        [54, 33, 91, 92, 62, 89, 39, 13, 17, 82],
        [ 2, 69, 95, 15, 43, 16, 15, 48, 67, 76],
        [45, 89, 48, 91, 39, 41, 43, 29, 82, 89],
        [20, 39, 44, 79, 68, 27, 16, 14, 55, 41],
        [12, 97, 36, 28, 43,  7,  7, 55, 33, 93],
        [51, 80, 75, 61, 29, 81, 20,  6, 80, 51],
        [95, 92,  6, 40, 50,  8,  8, 79, 60, 72],
        [44, 39, 30, 23, 22, 15, 52, 80, 21, 80]

In [131]:
x=np.where(x>=50,1,2)

In [132]:
x

array([[[2, 1, 2, 2, 1, 1, 1, 1, 1, 2],
        [1, 1, 1, 2, 1, 2, 2, 1, 1, 2],
        [1, 1, 1, 1, 2, 2, 2, 2, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 1, 2, 2],
        [1, 1, 1, 1, 1, 1, 2, 2, 2, 2],
        [1, 2, 2, 2, 2, 1, 2, 1, 2, 2],
        [2, 1, 2, 2, 2, 1, 1, 1, 2, 2],
        [2, 1, 2, 1, 2, 1, 1, 2, 1, 1],
        [2, 2, 2, 1, 1, 1, 2, 1, 2, 1],
        [2, 1, 2, 2, 1, 2, 1, 2, 1, 2]],

       [[1, 2, 2, 1, 1, 2, 2, 1, 2, 1],
        [1, 1, 2, 2, 2, 2, 2, 2, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 2, 2, 1],
        [2, 1, 1, 2, 2, 2, 2, 2, 1, 1],
        [2, 1, 2, 1, 2, 2, 2, 2, 1, 1],
        [2, 2, 2, 1, 1, 2, 2, 2, 1, 2],
        [2, 1, 2, 2, 2, 2, 2, 1, 2, 1],
        [1, 1, 1, 1, 2, 1, 2, 2, 1, 1],
        [1, 1, 2, 2, 1, 2, 2, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 1, 1, 2, 1]]])

In [133]:
x[1,5:10,5:10]

array([[2, 2, 2, 1, 2],
       [2, 2, 1, 2, 1],
       [1, 2, 2, 1, 1],
       [2, 2, 1, 1, 1],
       [2, 1, 1, 2, 1]])

In [ ]:
import pandas as pd

In [135]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [136]:
np.where(a>4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [139]:
import pandas as pd
x = [1,2,3,4,5]
s= pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [140]:
print(s.index)

RangeIndex(start=0, stop=5, step=1)


In [141]:
s.values

array([1, 2, 3, 4, 5], dtype=int64)

In [143]:
type(s.values)

numpy.ndarray

In [144]:
s = pd.Series(x, index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [145]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [146]:
s['c']

3

In [147]:
s[2]

3

In [148]:
s[['b','d']]

b    2
d    4
dtype: int64

In [149]:
s[[0,3]]

a    1
d    4
dtype: int64

In [150]:
s.a

1

In [151]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [152]:
x['수학']

90

In [153]:
x['영어':]

영어    80
과학    95
미술    80
dtype: int64

In [154]:
part = pd.Series(x, index = ["수학", "영어", "과학"])

In [155]:
part

수학    90
영어    80
과학    95
dtype: int64

In [163]:
student_1 = {"수학":90, "영어":80, "과학":95, "미술":80}
student_2 = {"수학":70, "영어":90, "과학":100, "미술":70}

index_1= ["홍길동" for i in range(len(student_1))] + ["이몽룡" for i in range(len(student_2))]


In [164]:
index_1

['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [165]:
index_2= list(student_1.keys()) + list(student_2.keys())
index_2

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [166]:
value_all = list(student_1.values()) + list(student_2.values())
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [169]:
students = pd.Series(value_all,index=[index_1,index_2])
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64